// Generated by scripts/font-pack.mjs from assets/fonts/minogram_6x10/{png,xml}.
// The 39 glyphs the game draws — space + - 0-9 A-Z — at 6x10, 390 bytes.
// Selected with GLYPH_SOURCE === 'minogram'.
import type { BitmapFont } from './BitmapGlyphs';

const PACKED = 'AAAAAAAAAAAAAAAACAg+CAgAAAAAAAAAPgAAAAAAABwiJioyIhwAAAAIGAgICAg+AAAAHCICBAgQPgAAABwiAgwCIhwAAAAiIiI+AgICAAAAPiAgPAIiHAAAABwgIDwiIhwAAAA+AgIECAgIAAAAHCIiHCIiHAAAABwiIh4CIhwAAAAcIiIiPiIiAAAAPCIiPCIiPAAAABwiICAgIhwAAAA8IiIiIiI8AAAAPiAgPCAgPgAAAD4gIDwgICAAAAAcIiAuIiIcAAAAIiIiPiIiIgAAAD4ICAgICD4AAAACAgICIiIcAAAAIiQoMCgkIgAAACAgICAgID4AAAAiNioiIiIiAAAAIiIyKiYiIgAAABwiIiIiIhwAAAA8IiI8ICAgAAAAHCIiIiIiHAYAADwiIjwiIiIAAAAcIiAcAiIcAAAAPggICAgICAAAACIiIiIiIhwAAAAiIiIiFBQIAAAAIiIiIio2IgAAACIiFAgUIiIAAAAiIhQICAgIAAAAPgIECBAgPgAA';

function unpack(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const MINOGRAM_FONT: BitmapFont = {
  w: 6,
  h: 10,
  data: /*#__PURE__*/ unpack(PACKED),
  indexOf: (ch) => {
    const c = ch.charCodeAt(0);
    if (c === 0x20) return 0;
    if (c === 0x2b) return 1; // +
    if (c === 0x2d) return 2; // -
    if (c >= 0x30 && c <= 0x39) return 3 + (c - 0x30);  // 0-9  -> 3..12
    if (c >= 0x41 && c <= 0x5a) return 13 + (c - 0x41); // A-Z  -> 13..38
    return -1;
  },
};
