// Generated by scripts/font-pack.mjs from assets/fonts/monogram/bitmap/monogram-bitmap.json.
// The 39 glyphs the game draws — space + - 0-9 A-Z — at 5x12, 468 bytes.
// Selected with GLYPH_SOURCE === 'monogram'.
import type { BitmapFont } from './BitmapGlyphs';

const PACKED = 'AAAAAAAAAAAAAAAAAAAAAAQEHwQEAAAAAAAAAAAAHwAAAAAAAAAADhETFRkRDgAAAAAABAwEBAQEHwAAAAAADhEBAgQIHwAAAAAADhEBBgERDgAAAAAACQkRHwEBAQAAAAAAHxAeAQERDgAAAAAADhAQHhERDgAAAAAAHwEBAgQEBAAAAAAADhERDhERDgAAAAAADhERDwERDgAAAAAADhERER8REQAAAAAAHhERHhERHgAAAAAADhEQEBARDgAAAAAAHhERERERHgAAAAAAHxAQHhAQHwAAAAAAHxAQHhAQEAAAAAAADhEQFxERDgAAAAAAERERHxEREQAAAAAAHwQEBAQEHwAAAAAAAQEBARERDgAAAAAAERIUGBQSEQAAAAAAEBAQEBAQHwAAAAAAERsVEREREQAAAAAAEREZFRMREQAAAAAADhERERERDgAAAAAAHhERHhAQEAAAAAAADhERERERDgMAAAAAHhERHhEREQAAAAAADhEQDgERDgAAAAAAHwQEBAQEBAAAAAAAERERERERDgAAAAAAEREREQoKBAAAAAAAERERERUbEQAAAAAAEREKBAoREQAAAAAAEREKBAQEBAAAAAAAHwECBAgQHwAA';

function unpack(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const MONOGRAM_FONT: BitmapFont = {
  w: 5,
  h: 12,
  data: /*#__PURE__*/ unpack(PACKED),
  indexOf: (ch) => {
    const c = ch.charCodeAt(0);
    if (c === 0x20) return 0;
    if (c === 0x2b) return 1; // +
    if (c === 0x2d) return 2; // -
    if (c >= 0x30 && c <= 0x39) return 3 + (c - 0x30);  // 0-9  -> 3..12
    if (c >= 0x41 && c <= 0x5a) return 13 + (c - 0x41); // A-Z  -> 13..38
    return -1;
  },
};
