// Generated by scripts/font-pack.mjs from assets/fonts/round_6x6.{png,xml}.
// The 39 glyphs the game draws — space + - 0-9 A-Z — at 6x6, 234 bytes.
// Selected with GLYPH_SOURCE === 'round6'.
import type { BitmapFont } from './BitmapGlyphs';

const PACKED = 'AAAAAAAACAg+CAgAAAA+AAAAHCIiIhwAOAgICD4APAIeID4APgIOAj4AIiI+AgIAPiA8AjwAHCA8IhwAPgIECAgAHCIcIhwAHCIeAjwAHCI+IiIAPCI8IjwAHCIgIhwAPCIiIjwAPiA4ID4APiA4ICAAHCAuIhwAIiI+IiIAPggICD4AAgICIhwAIiQ4JCIAICAgID4AIjYqIiIAIjIqJiIAHCIiIhwAPCI8ICAAHCIqJBoAPCI8JCIAHiAcAjwAPggICAgAIiIiIhwAIiIiFAgAIiIqNiIAIhQIFCIAIhQICAgAPgQIED4A';

function unpack(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const ROUND6_FONT: BitmapFont = {
  w: 6,
  h: 6,
  data: /*#__PURE__*/ unpack(PACKED),
  indexOf: (ch) => {
    const c = ch.charCodeAt(0);
    if (c === 0x20) return 0;
    if (c === 0x2b) return 1; // +
    if (c === 0x2d) return 2; // -
    if (c >= 0x30 && c <= 0x39) return 3 + (c - 0x30);  // 0-9  -> 3..12
    if (c >= 0x41 && c <= 0x5a) return 13 + (c - 0x41); // A-Z  -> 13..38
    return -1;
  },
};
