// Generated by scripts/font-pack.mjs from assets/fonts/square_6x6/{png,xml}.
// The 39 glyphs the game draws — space + - 0-9 A-Z — at 6x6, 234 bytes.
// Selected with GLYPH_SOURCE === 'square6'.
import type { BitmapFont } from './BitmapGlyphs';

const PACKED = 'AAAAAAAACAg+CAgAAAA+AAAAPiIiIj4AOAgICD4APgI+ID4APgIOAj4AIiI+AgIAPiA+Aj4APiA+Ij4APgICAgIAPiI+Ij4APiI+AgIAPiI+IiIAPiI8Ij4APiAgID4APCIiIjwAPiA4ID4APiA4ICAAPiAuIj4AIiI+IiIAPggICD4AAgICIj4AIiQ4JCIAICAgID4AIjYqIiIAIjIqJiIAPiIiIj4APiI+ICAAPiIqJj4APiI+JCIAPiA+Aj4APggICAgAIiIiIj4AIiIiFAgAIiIqNiIAIhQIFCIAIiI+CAgAPgQIED4A';

function unpack(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const SQUARE6_FONT: BitmapFont = {
  w: 6,
  h: 6,
  data: /*#__PURE__*/ unpack(PACKED),
  indexOf: (ch) => {
    const c = ch.charCodeAt(0);
    if (c === 0x20) return 0;
    if (c === 0x2b) return 1; // +
    if (c === 0x2d) return 2; // -
    if (c >= 0x30 && c <= 0x39) return 3 + (c - 0x30);  // 0-9  -> 3..12
    if (c >= 0x41 && c <= 0x5a) return 13 + (c - 0x41); // A-Z  -> 13..38
    return -1;
  },
};
